### ISSUE TITLE
installation issues => ERROR: compilation failed for package 'DreamAI'

### ISSUE THREAD

**Issue by ihorrible** [WangLab-MSSM/DreamAI#11]
Hi everyone! I am would like to use NAguideR (https://github.com/wangshisheng/NAguideR) which requires Dream AI package, but I cannot install the Dream AI because of the following error: 

![Error](https://user-images.githubusercontent.com/63013549/155314580-b733225e-9fae-4ae4-9ac9-856b6ee22090.PNG)
![dreamai](https://user-images.githubusercontent.com/63013549/155314586-e04b5a96-88e5-42a1-8566-4916a1e5a1e3.PNG)

> remotes::install_github("WangLab-MSSM/DreamAI/Code")
Downloading GitHub repo WangLab-MSSM/DreamAI@HEAD
√  checking for file 'C:\Users\iataraskin\AppData\Local\Temp\RtmpiCzuU7\remotes3594182526e3\WangLab-MSSM-DreamAI-7e395b3\Code/DESCRIPTION' (477ms)
-  preparing 'DreamAI': (1s)
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories (339ms)
-  building 'DreamAI_0.1.0.tar.gz'
   
Устанавливаю пакет в ‘C:/Users/iataraskin/Documents/R/win-library/4.1’
(потому что ‘lib’ не определено)
* installing *source* package 'DreamAI' ...
** using staged installation
** libs

*** arch - i386
"c:/rtools40/mingw32/bin/"g++ -std=gnu++11  -I"C:/PROGRA~1/R/R-41~1.2/include" -DNDEBUG  -I'C:/Users/iataraskin/Documents/R/win-library/4.1/Rcpp/include'        -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c dummy.cpp -o dummy.o
sh: line 1: c:/rtools40/mingw32/bin/g++: No such file or directory
make: *** [C:/PROGRA~1/R/R-41~1.2/etc/i386/Makeconf:245: dummy.o] Error 127
ERROR: compilation failed for package 'DreamAI'
* removing 'C:/Users/iataraskin/Documents/R/win-library/4.1/DreamAI'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/IATARA~1/AppData/Local/Temp/RtmpiCzuU7/file35946dde2276/DreamAI_0.1.0.tar.gz’ had non-zero exit status

**Comment by annapamma** [comment]
Hi @ihorrible !

What version of R are you using? (From the error message, it looks like it might be 4.1. Can you try it with 3.5?) 

And do you have Rtools installed? 

Thanks!

**Comment by ihorrible** [comment]
> Hi @ihorrible !
> 
> What version of R are you using? (From the error message, it looks like it might be 4.1. Can you try it with 3.5?)
> 
> And do you have Rtools installed?
> 
> Thanks!

Hi @annapamma Yes, I have Rtools installed. Any other options I can leave my version 4.1 ? (3.5 seems to be out of date a little bit))

**Comment by ihorrible** [comment]
I re-install Rtools and leave my version of R as 4.1 and now everything works ) 

https://github.com/wangshisheng/NAguideR/issues/2

**Comment by annapamma** [comment]
Thank you for the update! I'll go ahead and close this then.
